spring:
  cloud:
    gateway:
      routes[0]:
        id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        filters:
          AuthenticationFilter
  application:
    name: Gateway Service


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

jwt:
  secret: 8nwoHFwkdQ1Uy/EhOBJwiabfHoMCREkD+KC149Wq+5oo00+cHcl4VeWn+n0LJpQ4
logging:
  level:
    web: debug
