spring:
  application:
    name: User Service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userdb?useSSl=false
    username: root
    password: Rootdatabase
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

server:
  port: 8081
